### ISSUE TITLE
Using aioconsole for the CLI?

### ISSUE THREAD

**Issue by vxgmichel** [aio-libs/aiomonitor#14]
Since [aioconsole](https://github.com/vxgmichel/aioconsole) is already part of the requirements, you might want to take advantage of its [CLI capabilites](http://aioconsole.readthedocs.io/en/latest/#command-line-interfaces). Here's a [working re-implementation of aiomonitor](https://gist.github.com/vxgmichel/63493a6cd0831ca4cc84430ef1c61a0e). I can provide some help if necessary.

**Comment by jettify** [comment]
@vxgmichel Thanks! From first glance looks interesting.

**Comment by jettify** [comment]
I will review this more carefully a bit later

**Comment by achimnol** [comment]
It's already done.
