### ISSUE TITLE
v0.4.0 doesn't work on Python 3.5

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aiomonitor#159]
It contains Python 3.6-specific syntax at [this line](https://github.com/aio-libs/aiomonitor/blob/4a06de40a6cacac3074c76ececa1437565d6b3df/aiomonitor/monitor.py#L246).

**Comment by asvetlov** [comment]
I think dropping Python 3.5 support is fine, but trove classifiers should be updated.

**Comment by kxepal** [comment]
If it's about one single line, it's better to fix it. It seems like users are still expects 3.5 support.

**Comment by asvetlov** [comment]
Well, it is about a variable type annotation.
I prefer giving @jettify to decide.
Python 3.5 is not maintained by core devs anymore.
Even pull requests into 3.6 are forbidden now :)

**Comment by bmerry** [comment]
@asvetlov just because 3.5 is not being actively developed doesn't mean it's not being deployed. According to https://devguide.python.org/#status-of-python-branches it's still got until 2020-09-13 before being end-of-lifed.

I've submitted a PR to restore functionality on 3.5.2 (the version shipped with Ubuntu 16.04).

**Comment by bmerry** [comment]
If 3.5 is dropped in future, I would highly recommend shipping a final version that works with 3.5 before adding `python_requires` to setup.py. If I'm not mistaken, modern versions of pip will by default install the most recent version that is permitted by `python_requires`, and so it would be nice if people running 3.5 actually get a working version, particularly if it's implicitly sucked in by another dependency.

**Comment by asvetlov** [comment]
3.5 is not only not actively developed. 
The branch stopped to accept bug fixes.
Only security fixes could be backported, all work is done by the release manager (Larry for 3.5) manually.
No other core developer (like me) can commit into 3.5 branch.

**Comment by jettify** [comment]
new version on PyPI https://pypi.org/project/aiomonitor/0.4.1/

**Comment by jettify** [comment]
As for Python 3.5 support, I think once 3.8 out (https://www.python.org/dev/peps/pep-0569/#schedule) I am going to drop 3.5 support.

**Comment by bmerry** [comment]
Thanks!
