### ISSUE TITLE
Direction key seems not work in the aiomonitor console.

### ISSUE THREAD

**Issue by ryanrain2016** [aio-libs/aiomonitor#200]
Can't use direction key to navigate to history in the aiomonitor console. It is suggested to add directional key support

**Comment by jettify** [comment]
Sorry for delay you can use `rlwrap` trick as workaround:
```
rlwrap nc localhost 50101
```

**Comment by achimnol** [comment]
This now works with backports of aiomonitor-ng.
The next release will support the full terminal capability.
