### ISSUE TITLE
Can't use home / end / arrow keys in console

### ISSUE THREAD

**Issue by tannercollin** [aio-libs/aiomonitor#207]
Hi, I end up getting escape codes when I try to press the home / end / arrow keys in console:

![Screenshot from 2019-10-06 00-04-59](https://user-images.githubusercontent.com/6752449/66265050-f8801900-e7cc-11e9-95f0-7c1228a972b4.png)

Possible dupe of #200. I wasn't sure if he just meant history.

Would it possible to use a Readline interface? I noticed that aioconsole added support for it in https://github.com/vxgmichel/aioconsole/pull/9

Thanks

**Comment by jettify** [comment]
Sorry for delay you can use `rlwrap` trick as workaround:
```
rlwrap nc localhost 50101
```

**Comment by jettify** [comment]
Currently I do not have any plans to work on this feature, since `rlwrap` works well for me. Happy to review and accept PRs in this area.
