### ISSUE TITLE
Add `grep`-wise option on `ps`

### ISSUE THREAD

**Issue by sinwoobang** [aio-libs/aiomonitor#326]
Hello, I am glad to have found and be using this library.

However, when dealing with 1,000 tasks at once, I find it difficult to monitor the output using 'ps' on 'monitor'.
Would it be beneficial to have output cutting tools such as `grep`, `tail`, or `head`?

Thanks

**Comment by achimnol** [comment]
aiomonitor-ng will add `ps -f` / `ps --filter` which filters the list by task names or abbreviated coroutine names!
I think it would be a good idea to add `--head` and `--tail` options as well. I'm also considering a full pagination support as future work.

**Comment by achimnol** [comment]
Now it's included in both the terminal UI and the web UI.
Please open another issue if you have further suggestions to the current implementation.

**Comment by achimnol** [comment]
Now it's included in both the terminal UI and the web UI.
Please open another issue if you have further suggestions to the current implementation.
